### ISSUE TITLE
Rename Circuits for consistency

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/CircuitProcessing#6]
Current naming:

  | **Tier 1** | **Tier 2** | **Tier 3** | **Tier 4** | **Tier 5**
-- | -- | -- | -- | -- | --
**Primary** | Basic Circuit Board | Electronic Circuit | Advanced Circuit | Processing Unit | Advanced Processing Unit
**Secondary** |   | Basic Electronic Board | Electronic Circuit Board | Electronic Logic Board | Electronic Processing Board
**Tertiary** |   |   | Circuit Board | Superior Circuit Board | Multi-layer Circuit Board

Proposed naming;

  | **Tier 1** | **Tier 2** | **Tier 3** | **Tier 4** | **Tier 5**
-- | -- | -- | -- | -- | --
**Primary** | Basic Circuit | Electronic Circuit | Advanced Circuit | Processing Unit | Advanced Processing Unit
**Secondary** |   | Electronic Circuit Board | Advanced Circuit Board | Processing Board | Advanced Processing Board
**Tertiary** |   |   | Advanced Circuit Substrate | Processing Substrate | Advanced Processing Substrate

**Comment by KiwiHawk** [comment]
@shelaf I've updated how these items are being named. I'm no longer using the `localised_name` property. Can you check the Japanese translations please? Thanks!

**Comment by shelaf** [comment]
I opened PR https://github.com/KiwiHawk/CircuitProcessing/pull/20
